# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Pixelastic
tagline:          'You can cut our wings but we will always remember what it was like to fly.'
description:      'Personal blog of Tim Carry. Posting mostly on tech-related stuff.'
url:              http://blog.pixelastic.com
base_url:         blog.pixelastic.com

author:
  name:           'Tim Carry'
  url:            https://twitter.com/pixelastic

paginate:         5

# Custom vars
version:          3.0.0

github:
  repo:           https://github.com/pixelastic/blog.pixelastic.com

# Build
timezone:         "Europe/Paris"
encoding:         "utf-8"
exclude:          ['css']
